### ISSUE TITLE
Official support for signing and verifying via GitHub Actions

### ISSUE THREAD

**Issue by chipzoller** [sigstore/k8s-manifest-sigstore#105]
**Description**

Signing/verification through GitHub Actions is supported via cosign but there seem to be some difficulties with k8s-manifest-sigstore. Specifically, the subject either doesn't come through or the field isn't present. There are likely other incompatibilities.

**Comment by rurikudo** [comment]
@chipzoller I will look into this. Thank you

**Comment by chipzoller** [comment]
Closed by #107
