### ISSUE TITLE
Can this be updated to use cosing 1.13 ?

### ISSUE THREAD

**Issue by eddycharly** [sigstore/k8s-manifest-sigstore#94]
**Question**

This is blocking us from upgrading cosign.

**Comment by hirokuni-kitahara** [comment]
Thank you for your question.
The cosign version has been updated to v1.13.0 with the PR https://github.com/sigstore/k8s-manifest-sigstore/pull/95.

**Comment by hirokuni-kitahara** [comment]
yes, I will release v0.4.2 which contains the PR above now.
I will let you know once the version is released here.

**Comment by hirokuni-kitahara** [comment]
`v0.4.2` has been released now.
Please try it in your project! thank you.

**Comment by eddycharly** [comment]
@hirokuni-kitahara can we have a release using v1.13.1 ?

**Comment by hirokuni-kitahara** [comment]
Hi @eddycharly , we have released v0.4.3 which uses cosign v1.13.1.

**Comment by chipzoller** [comment]
I guess this issue can be closed now.

**Comment by hirokuni-kitahara** [comment]
yes, thank you very much :)
