### ISSUE TITLE
Generate SLSA Provenance on Release

### ISSUE THREAD

**Issue by joycebrum** [sigstore/k8s-manifest-sigstore#97]
**Description**

Hi, I'm Joyce, working on behalf of Google and the [Open Source Security Foundation](https://openssf.org/) to help essential open-source projects improve their supply-chain security. 

I would like to suggest the adoption of [SLSA](https://slsa.dev/) Level 3. SLSA aims to improve open source security by identifying best practices regarding artifact building processes and source code management. It does this by aligning these best practices with [levels](https://slsa.dev/spec/v0.1/levels) from 0 to 4, which describe how many best practices the project is using.

Concerning the build process, SLSA highlights the importance of granting the integrity of binaries or artifacts, so that it's ensured that a binary's code really comes from the source code you’re relying on. This assurance relies on the usage of a [provenance](https://slsa.dev/provenance), which is verifiable and relatable to the artifact, describing where, when and how it was produced.

It is extremely easy to achieve the SLSA Level 1, just by configuring the Provenance Generation. To see the steps that are necessary to achieve the SLSA Levels, take a look at [Getting Started at SLSA](https://slsa.dev/get-started). And, considering that you are already using github actions to generate builds and following the criterias to SLSA Level 3, only by enabling the slsa provenance generation you would achieve the SLSA Level 3. 

Would you be interested in a PR adding the provenance generation on your current build process? I've already created a fork to test if it would really be feasible to generate provenance using go-releaser, if you'd like to take a look at what I've done to enable it, it is in https://github.com/joycebrum/k8s-manifest-sigstore. Also an example of the artifact with provenance https://github.com/joycebrum/k8s-manifest-sigstore/actions/runs/3292435083.

I can also update the README to add:

- A brief paragraph to let your end-users know you generate provenance and guide them to verify it when downloading your artifacts.
- A SLSA 3 badge, to expose the current level of effort of the project around security and also to encourage new adopters of SLSA, to help raise the collective level of open source security.

**Comment by hirokuni-kitahara** [comment]
Hi Joyce, thank you very much for suggesting this.
I totally agree with your idea to generate SLSA provenance for the binaries released by this project.
Could you please submit a PR from your fork? Let's discuss in detail there.
Thank you.
